# Generated by Django 2.1.dev20180322075356 on 2018-03-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('complexity_id', models.AutoField(primary_key=True, serialize=False)),
                ('complexity', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('options', models.IntegerField(null=True)),
                ('is_correctanwser', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=60)),
                ('section_id', models.IntegerField(null=True)),
                ('created_by', models.CharField(max_length=60)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('complexity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionmanagement.Complexity')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('questiontype_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='questiontype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionmanagement.QuestionType'),
        ),
        migrations.AddField(
            model_name='questionchoices',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionmanagement.Questions'),
        ),
    ]
