# Generated by Django 2.1.dev20180322075356 on 2018-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoices',
            name='is_correctanwser',
            field=models.BooleanField(default=False),
        ),
    ]
